version: "3"
services:
  autocommit:
    image: alpine/autocommit:latest
    restart: always
    volumes:
      - /home/fouri/.ssh:/root/.ssh
      - /home/fouri/.auto:/autocommit
      - /home/fouri/.auto/.git:/autocommit/.git
    command:
      - /bin/sh
      - -ecx
      - |
       crond -f
       sleep infinity	
